### ISSUE TITLE
Implement cancel previous CI build for PRs

### ISSUE THREAD

**Issue by saw-jan** [gherlint/gherlint-vscode#12]
We might push frequently to the PRs which will cause CI builds to trigger for each push. In order to prevent the unnecessary usage of resources, we need to implement a way to cancel previous builds for Github action.

There is a Github action exactly for this: https://github.com/marketplace/actions/cancel-workflow-action

**Comment by grgprarup** [comment]
@saw-jan I would love to work on this. But it will take a bit long time to research and implement this. (Need self-research + guidance)
